title: DevPortfolio
email: budhram.gurung01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio Website of a Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: coolbrg
github_username:  coolbrg

google_analytics: # your google analytics id

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Build settings
markdown: kramdown
